version: "3.5"

x-app: &base-app
  build:
    context: .
    target: app
  depends_on:
    - database
    - azurite
  volumes:
    - ./src:/src
    - ./tests:/tests
    - ./deploy:/deploy
  ports:
    - "8000:8000"
  environment: &base-app-env
    SECRET_KEY: 'insecure'
    JWT_SECRET_KEY: 'insecure'
    DATABASE_HOST: 'database'
    AZURITE_STORAGE_CONNECTION_STRING: 'DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;'
    AZURITE_QUEUE_CONNECTION_STRING: 'DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;QueueEndpoint=http://azurite:10001/devstoreaccount1;'

services:
  database:
    image: postgres:15
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
  
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"  # Blob service
      - "10001:10001"  # Queue service

  app:
    <<: *base-app
    build:
      context: .
      target: app
    image: ${REGISTRY:-localhost:5000}/${REPOSITORY:-opdrachten/iiif-auth-proxy}:${VERSION:-latest}
    command: /deploy/docker-run.sh

  dev:
    <<: *base-app
    build:
      context: .
      target: dev
    environment:
      <<: *base-app-env
      DEBUG: 'true'
      USE_JWKS_TEST_KEY: 'true'
      MOCK_GET_IMAGE_FROM_SERVER: 'true'
      METADATA_SERVER_BASE_URL: 'http://metadata-server:8000'
    volumes:
    - ./static:/static
    command: python manage.py runserver 0.0.0.0:8000

  test:
    <<: *base-app
    build:
      context: .
      target: tests
    environment:
      <<: *base-app-env
      DJANGO_SETTINGS_MODULE: "main.settings"
      USE_JWKS_TEST_KEY: 'true'