trigger:
  batch: true
  branches:
    include:
      - main
  tags:
    include:
      - "*.*.*"

parameters:
  - name: versionOverride
    displayName: "[OPTIONAL] Build/deploy version override"
    type: string
    default: ' '

variables:
  # Debugging
  System.Debug: true

resources:
  repositories:
    - repository: templates
      type: git
      name: opdrachten/templates
      ref: main

extends:
  template: pipelines/aks/template.yaml@templates
  parameters:
    name: iiif-auth-proxy
    ${{ if ne(parameters.versionOverride, ' ') }}:
      version: ${{ parameters.versionOverride }}
      build:
        producedImages:
        - opdrachten/iiif-auth-proxy-dev
        - opdrachten/iiif-auth-proxy-test
    dev:
      pool: Opdrachten
      namespace: ns-ccc-opdr-ont-01-bouwdossiers
      kubernetesServiceConnection: "SCN-K8S-ns-ccc-opdr-ont-01-bouwdossiers"
      preSteps:
        - script: helm uninstall iiif-auth-proxy -n ns-ccc-opdr-ont-01-bouwdossiers || true
