name: Opdrachten Team Dependabot

on:
  schedule: # Run the script on the 1st and 15th of every month
    - cron: '0 6 1,15 * *'
  workflow_dispatch: # Creates button on Github to trigger the workflow manually


jobs:
  dependabot:
    name: Templates
    uses: amsterdam/github-workflows/.github/workflows/dependabot.yml@v1
    secrets: inherit  # Inherit secrets from the repository. You need to define "SLACK_TOKEN" in settings -> secrets -> actions!
    with:
      check_diff: false  # Create a list of major upgrades. Needs the Makefile target "diff"
      slack_channel: 'opdrachten-dependabot'  # Slack channel to post release steps to
      timetell_code: 21079  # Timetell project id
      acceptance_pipeline: "https://dev.azure.com/CloudCompetenceCenter/Opdrachten/_build?definitionId=2631"
      production_pipeline: "https://dev.azure.com/CloudCompetenceCenter/Opdrachten/_build?definitionId=2631"
      acceptance_urls: "https://acc.dataportaal.amsterdam.nl/data/bouwdossiers/bouwdossier/SJ93/?center=52.369701%2C4.8632354&term=Baarsjesweg+36%2C+1057HL+Amsterdam&zoom=14"
      production_urls: "https://data.amsterdam.nl/data/bouwdossiers/bouwdossier/SJ93/?center=52.369701%2C4.8632354&term=Baarsjesweg+36%2C+1057HL+Amsterdam&zoom=14"
